# documentation: https://help.github.com/en/articles/workflow-syntax-for-github-actions
name: deploy documentation (only on push to main branch)
on:
  push:
    branches: main
jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
    - name: checkout
      uses: actions/checkout@v2

    - name: set up Python
      uses: actions/setup-python@v1
      with:
        python-version: '3.10'

    - name: install mkdocs
      run: |
          pip install mkdocs mkdocs-material mkdocs-git-revision-date-localized-plugin mkdocs-toc-sidebar-plugin
          mkdocs --version

    - name: build tutorial
      run: make test && make deploy
